frr version 8.4
frr defaults traditional
hostname r2
log stdout
service integrated-vtysh-config
!
agentx
!
router bgp 65002
 bgp router-id 2.2.2.2
 no bgp ebgp-requires-policy
 neighbor 10.0.12.1 remote-as 65001
 timers bgp 3 9
 !
 address-family ipv4 unicast
  network 2.2.2.2/32
  network 192.168.2.0/24
 exit-address-family
!
ip route 2.2.2.2/32 lo
!
line vty
